title: Natural Science Text Reuse in Early Victorian Knowledge Periodicals
email: omonroe2@illinois.edu
description: by Owen Monroe

url: "https://owenmonroe.github.io/knowledge_periodicals_text_reuse/"

github_username:  owenmonroe

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
